version: '3'
services:

  db:
    container_name: db
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      # - POSTGRES_DB=$DB_NAME
      # - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    expose:
      - $DB_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $DB_NAME"]
      interval: $INTERVAL
      timeout: $TIMEOUT
      retries: $RETRIES
      start_period: $START_PERIOD

  backend:
    container_name: backend
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    command: bash -c "alembic upgrade head && uvicorn app.main:app --reload --host=0.0.0.0"
    # command: bash -c "uvicorn app.main:app --reload --host=0.0.0.0"
    volumes:
      - ../../app:/app/app
    # restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    env_file:
      - ../../.env


volumes:
  db_data:
