"""empty message

Revision ID: 6f5b39d082a2
Revises:
Create Date: 2024-05-24 13:08:30.197388

"""

from typing import Sequence

import sqlalchemy as sa
from fastapi_users_db_sqlalchemy import generics

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f5b39d082a2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

    op.create_table(
        "salary",
        sa.Column("value", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("inc_date", sa.Date(), nullable=True),
        sa.Column("user_id", generics.GUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_salary_user_id_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_salary")),
        sa.UniqueConstraint("user_id", name=op.f("uq_salary_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("salary")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    # ### end Alembic commands ###
