name: CI/CD

on:
  push:
    branches: ["develop"]
  workflow_dispatch:

jobs:

  tests:
    uses: ./.github/workflows/tests.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}

  build_and_push_to_docker_hub:
    needs: tests
    uses: ./.github/workflows/build_push.yml
    secrets: inherit

  server_environment:
    needs: tests
    uses: ./.github/workflows/server_environ.yml
    secrets: inherit

  deploy:
    needs: [build_and_push_to_docker_hub, server_environment]
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
