version: '3'
services:

  db:
    container_name: db
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      # - POSTGRES_DB=$DB_NAME
      # - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    expose:
      - $DB_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $DB_NAME"]
      interval: $INTERVAL
      timeout: $TIMEOUT
      retries: $RETRIES
      start_period: $START_PERIOD

  backend:
    container_name: backend
    image: "${DOCKERHUB_USERNAME}/${PROJECT_NAME}"
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host=0.0.0.0"
    restart: always
    depends_on:
      db:
        condition: service_healthy
    expose:
      - 8000
    env_file:
      - ./.env

  nginx:
    container_name: swag
    image: linuxserver/swag:2.4.0
    restart: unless-stopped
    depends_on:
      - backend
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=${DOMAIN}
      - VALIDATION=http
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./nginx.conf:/config/nginx/site-confs/default.conf

volumes:
  db_data:
